### ISSUE TITLE
Cannot perform action error

### ISSUE THREAD

**Issue by sina-masoud-ansari** [sina-masoud-ansari/pymarl#1]
[INFO 06:42:22] my_main t_env: 2854007 / 10050000
[INFO 06:42:22] my_main Estimated time left: 8 hours, 10 minutes, 3 seconds. Time passed: 3 hours, 17 minutes, 31 seconds
[INFO 06:42:35] my_main Updated target network
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/pymarl/src/runners/parallel_runner.py", line 221, in env_worker
    reward, terminated, env_info = env.step(actions)
  File "/usr/local/lib/python3.5/dist-packages/smac/env/starcraft2/starcraft2.py", line 373, in step
    agent_action = self.get_agent_action(a_id, action)
  File "/usr/local/lib/python3.5/dist-packages/smac/env/starcraft2/starcraft2.py", line 439, in get_agent_action
    "Agent {} cannot perform action {}".format(a_id, action)
AssertionError: Agent 1 cannot perform action 0

**Comment by sina-masoud-ansari** [comment]
assuming upstream fixes for this, closing for now
